ALTER TABLE inventory_items
    ADD COLUMN IF NOT EXISTS upgrade_hp INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_atk INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_def INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_spd INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_crit_rate NUMERIC(5,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_crit_dmg NUMERIC(5,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_eva NUMERIC(5,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upgrade_lifesteal NUMERIC(5,2) DEFAULT 0;
